/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as ResetRouteImport } from "./routes/reset"
import { Route as RegisterRouteImport } from "./routes/register"
import { Route as PrivacyRouteImport } from "./routes/privacy"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as DownloadRouteImport } from "./routes/download"
import { Route as AuthenticatedRouteRouteImport } from "./routes/_authenticated/route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as InviteCodeRouteImport } from "./routes/invite/$code"
import { Route as UsersUsernameRouteRouteImport } from "./routes/users/$username/route"
import { Route as AuthenticatedSpacesRouteRouteImport } from "./routes/_authenticated/spaces/route"
import { Route as AuthenticatedProfileRouteRouteImport } from "./routes/_authenticated/profile/route"
import { Route as AuthenticatedFeedRouteRouteImport } from "./routes/_authenticated/feed/route"
import { Route as AuthenticatedAvatarRouteRouteImport } from "./routes/_authenticated/avatar/route"
import { Route as AuthenticatedAtmeRouteRouteImport } from "./routes/_authenticated/@me/route"
import { Route as AuthenticatedFeedIndexRouteImport } from "./routes/_authenticated/feed/index"
import { Route as AuthenticatedFeedScheduledRouteImport } from "./routes/_authenticated/feed/scheduled"
import { Route as AuthenticatedFeedSavedRouteImport } from "./routes/_authenticated/feed/saved"
import { Route as AuthenticatedFeedFriendsRouteImport } from "./routes/_authenticated/feed/friends"
import { Route as AuthenticatedAtmeFriendsRouteImport } from "./routes/_authenticated/@me/friends"
import { Route as AuthenticatedSpacesSpaceIdRouteRouteImport } from "./routes/_authenticated/spaces/$spaceId/route"
import { Route as AuthenticatedAtmeChannelIdRouteRouteImport } from "./routes/_authenticated/@me/$channelId/route"
import { Route as AuthenticatedFeedPostsPostIdRouteImport } from "./routes/_authenticated/feed/posts/$postId"
import { Route as AuthenticatedSpacesSpaceIdChannelIdRouteRouteImport } from "./routes/_authenticated/spaces/$spaceId/$channelId/route"

const ResetRoute = ResetRouteImport.update({
  id: "/reset",
  path: "/reset",
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: "/download",
  path: "/download",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: "/invite/$code",
  path: "/invite/$code",
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUsernameRouteRoute = UsersUsernameRouteRouteImport.update({
  id: "/users/$username",
  path: "/users/$username",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSpacesRouteRoute =
  AuthenticatedSpacesRouteRouteImport.update({
    id: "/spaces",
    path: "/spaces",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRouteRoute =
  AuthenticatedProfileRouteRouteImport.update({
    id: "/profile",
    path: "/profile",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeedRouteRoute = AuthenticatedFeedRouteRouteImport.update({
  id: "/feed",
  path: "/feed",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvatarRouteRoute =
  AuthenticatedAvatarRouteRouteImport.update({
    id: "/avatar",
    path: "/avatar",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtmeRouteRoute = AuthenticatedAtmeRouteRouteImport.update({
  id: "/@me",
  path: "/@me",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedIndexRoute = AuthenticatedFeedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthenticatedFeedRouteRoute,
} as any)
const AuthenticatedFeedScheduledRoute =
  AuthenticatedFeedScheduledRouteImport.update({
    id: "/scheduled",
    path: "/scheduled",
    getParentRoute: () => AuthenticatedFeedRouteRoute,
  } as any)
const AuthenticatedFeedSavedRoute = AuthenticatedFeedSavedRouteImport.update({
  id: "/saved",
  path: "/saved",
  getParentRoute: () => AuthenticatedFeedRouteRoute,
} as any)
const AuthenticatedFeedFriendsRoute =
  AuthenticatedFeedFriendsRouteImport.update({
    id: "/friends",
    path: "/friends",
    getParentRoute: () => AuthenticatedFeedRouteRoute,
  } as any)
const AuthenticatedAtmeFriendsRoute =
  AuthenticatedAtmeFriendsRouteImport.update({
    id: "/friends",
    path: "/friends",
    getParentRoute: () => AuthenticatedAtmeRouteRoute,
  } as any)
const AuthenticatedSpacesSpaceIdRouteRoute =
  AuthenticatedSpacesSpaceIdRouteRouteImport.update({
    id: "/$spaceId",
    path: "/$spaceId",
    getParentRoute: () => AuthenticatedSpacesRouteRoute,
  } as any)
const AuthenticatedAtmeChannelIdRouteRoute =
  AuthenticatedAtmeChannelIdRouteRouteImport.update({
    id: "/$channelId",
    path: "/$channelId",
    getParentRoute: () => AuthenticatedAtmeRouteRoute,
  } as any)
const AuthenticatedFeedPostsPostIdRoute =
  AuthenticatedFeedPostsPostIdRouteImport.update({
    id: "/posts/$postId",
    path: "/posts/$postId",
    getParentRoute: () => AuthenticatedFeedRouteRoute,
  } as any)
const AuthenticatedSpacesSpaceIdChannelIdRouteRoute =
  AuthenticatedSpacesSpaceIdChannelIdRouteRouteImport.update({
    id: "/$channelId",
    path: "/$channelId",
    getParentRoute: () => AuthenticatedSpacesSpaceIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/download": typeof DownloadRoute
  "/login": typeof LoginRoute
  "/privacy": typeof PrivacyRoute
  "/register": typeof RegisterRoute
  "/reset": typeof ResetRoute
  "/@me": typeof AuthenticatedAtmeRouteRouteWithChildren
  "/avatar": typeof AuthenticatedAvatarRouteRoute
  "/feed": typeof AuthenticatedFeedRouteRouteWithChildren
  "/profile": typeof AuthenticatedProfileRouteRoute
  "/spaces": typeof AuthenticatedSpacesRouteRouteWithChildren
  "/users/$username": typeof UsersUsernameRouteRoute
  "/invite/$code": typeof InviteCodeRoute
  "/@me/$channelId": typeof AuthenticatedAtmeChannelIdRouteRoute
  "/spaces/$spaceId": typeof AuthenticatedSpacesSpaceIdRouteRouteWithChildren
  "/@me/friends": typeof AuthenticatedAtmeFriendsRoute
  "/feed/friends": typeof AuthenticatedFeedFriendsRoute
  "/feed/saved": typeof AuthenticatedFeedSavedRoute
  "/feed/scheduled": typeof AuthenticatedFeedScheduledRoute
  "/feed/": typeof AuthenticatedFeedIndexRoute
  "/spaces/$spaceId/$channelId": typeof AuthenticatedSpacesSpaceIdChannelIdRouteRoute
  "/feed/posts/$postId": typeof AuthenticatedFeedPostsPostIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/download": typeof DownloadRoute
  "/login": typeof LoginRoute
  "/privacy": typeof PrivacyRoute
  "/register": typeof RegisterRoute
  "/reset": typeof ResetRoute
  "/@me": typeof AuthenticatedAtmeRouteRouteWithChildren
  "/avatar": typeof AuthenticatedAvatarRouteRoute
  "/profile": typeof AuthenticatedProfileRouteRoute
  "/spaces": typeof AuthenticatedSpacesRouteRouteWithChildren
  "/users/$username": typeof UsersUsernameRouteRoute
  "/invite/$code": typeof InviteCodeRoute
  "/@me/$channelId": typeof AuthenticatedAtmeChannelIdRouteRoute
  "/spaces/$spaceId": typeof AuthenticatedSpacesSpaceIdRouteRouteWithChildren
  "/@me/friends": typeof AuthenticatedAtmeFriendsRoute
  "/feed/friends": typeof AuthenticatedFeedFriendsRoute
  "/feed/saved": typeof AuthenticatedFeedSavedRoute
  "/feed/scheduled": typeof AuthenticatedFeedScheduledRoute
  "/feed": typeof AuthenticatedFeedIndexRoute
  "/spaces/$spaceId/$channelId": typeof AuthenticatedSpacesSpaceIdChannelIdRouteRoute
  "/feed/posts/$postId": typeof AuthenticatedFeedPostsPostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_authenticated": typeof AuthenticatedRouteRouteWithChildren
  "/download": typeof DownloadRoute
  "/login": typeof LoginRoute
  "/privacy": typeof PrivacyRoute
  "/register": typeof RegisterRoute
  "/reset": typeof ResetRoute
  "/_authenticated/@me": typeof AuthenticatedAtmeRouteRouteWithChildren
  "/_authenticated/avatar": typeof AuthenticatedAvatarRouteRoute
  "/_authenticated/feed": typeof AuthenticatedFeedRouteRouteWithChildren
  "/_authenticated/profile": typeof AuthenticatedProfileRouteRoute
  "/_authenticated/spaces": typeof AuthenticatedSpacesRouteRouteWithChildren
  "/users/$username": typeof UsersUsernameRouteRoute
  "/invite/$code": typeof InviteCodeRoute
  "/_authenticated/@me/$channelId": typeof AuthenticatedAtmeChannelIdRouteRoute
  "/_authenticated/spaces/$spaceId": typeof AuthenticatedSpacesSpaceIdRouteRouteWithChildren
  "/_authenticated/@me/friends": typeof AuthenticatedAtmeFriendsRoute
  "/_authenticated/feed/friends": typeof AuthenticatedFeedFriendsRoute
  "/_authenticated/feed/saved": typeof AuthenticatedFeedSavedRoute
  "/_authenticated/feed/scheduled": typeof AuthenticatedFeedScheduledRoute
  "/_authenticated/feed/": typeof AuthenticatedFeedIndexRoute
  "/_authenticated/spaces/$spaceId/$channelId": typeof AuthenticatedSpacesSpaceIdChannelIdRouteRoute
  "/_authenticated/feed/posts/$postId": typeof AuthenticatedFeedPostsPostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/download"
    | "/login"
    | "/privacy"
    | "/register"
    | "/reset"
    | "/@me"
    | "/avatar"
    | "/feed"
    | "/profile"
    | "/spaces"
    | "/users/$username"
    | "/invite/$code"
    | "/@me/$channelId"
    | "/spaces/$spaceId"
    | "/@me/friends"
    | "/feed/friends"
    | "/feed/saved"
    | "/feed/scheduled"
    | "/feed/"
    | "/spaces/$spaceId/$channelId"
    | "/feed/posts/$postId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/download"
    | "/login"
    | "/privacy"
    | "/register"
    | "/reset"
    | "/@me"
    | "/avatar"
    | "/profile"
    | "/spaces"
    | "/users/$username"
    | "/invite/$code"
    | "/@me/$channelId"
    | "/spaces/$spaceId"
    | "/@me/friends"
    | "/feed/friends"
    | "/feed/saved"
    | "/feed/scheduled"
    | "/feed"
    | "/spaces/$spaceId/$channelId"
    | "/feed/posts/$postId"
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/download"
    | "/login"
    | "/privacy"
    | "/register"
    | "/reset"
    | "/_authenticated/@me"
    | "/_authenticated/avatar"
    | "/_authenticated/feed"
    | "/_authenticated/profile"
    | "/_authenticated/spaces"
    | "/users/$username"
    | "/invite/$code"
    | "/_authenticated/@me/$channelId"
    | "/_authenticated/spaces/$spaceId"
    | "/_authenticated/@me/friends"
    | "/_authenticated/feed/friends"
    | "/_authenticated/feed/saved"
    | "/_authenticated/feed/scheduled"
    | "/_authenticated/feed/"
    | "/_authenticated/spaces/$spaceId/$channelId"
    | "/_authenticated/feed/posts/$postId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DownloadRoute: typeof DownloadRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetRoute: typeof ResetRoute
  UsersUsernameRouteRoute: typeof UsersUsernameRouteRoute
  InviteCodeRoute: typeof InviteCodeRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/reset": {
      id: "/reset"
      path: "/reset"
      fullPath: "/reset"
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/privacy": {
      id: "/privacy"
      path: "/privacy"
      fullPath: "/privacy"
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/download": {
      id: "/download"
      path: "/download"
      fullPath: "/download"
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated": {
      id: "/_authenticated"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/invite/$code": {
      id: "/invite/$code"
      path: "/invite/$code"
      fullPath: "/invite/$code"
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/users/$username": {
      id: "/users/$username"
      path: "/users/$username"
      fullPath: "/users/$username"
      preLoaderRoute: typeof UsersUsernameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated/spaces": {
      id: "/_authenticated/spaces"
      path: "/spaces"
      fullPath: "/spaces"
      preLoaderRoute: typeof AuthenticatedSpacesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/profile": {
      id: "/_authenticated/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof AuthenticatedProfileRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/feed": {
      id: "/_authenticated/feed"
      path: "/feed"
      fullPath: "/feed"
      preLoaderRoute: typeof AuthenticatedFeedRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/avatar": {
      id: "/_authenticated/avatar"
      path: "/avatar"
      fullPath: "/avatar"
      preLoaderRoute: typeof AuthenticatedAvatarRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/@me": {
      id: "/_authenticated/@me"
      path: "/@me"
      fullPath: "/@me"
      preLoaderRoute: typeof AuthenticatedAtmeRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/feed/": {
      id: "/_authenticated/feed/"
      path: "/"
      fullPath: "/feed/"
      preLoaderRoute: typeof AuthenticatedFeedIndexRouteImport
      parentRoute: typeof AuthenticatedFeedRouteRoute
    }
    "/_authenticated/feed/scheduled": {
      id: "/_authenticated/feed/scheduled"
      path: "/scheduled"
      fullPath: "/feed/scheduled"
      preLoaderRoute: typeof AuthenticatedFeedScheduledRouteImport
      parentRoute: typeof AuthenticatedFeedRouteRoute
    }
    "/_authenticated/feed/saved": {
      id: "/_authenticated/feed/saved"
      path: "/saved"
      fullPath: "/feed/saved"
      preLoaderRoute: typeof AuthenticatedFeedSavedRouteImport
      parentRoute: typeof AuthenticatedFeedRouteRoute
    }
    "/_authenticated/feed/friends": {
      id: "/_authenticated/feed/friends"
      path: "/friends"
      fullPath: "/feed/friends"
      preLoaderRoute: typeof AuthenticatedFeedFriendsRouteImport
      parentRoute: typeof AuthenticatedFeedRouteRoute
    }
    "/_authenticated/@me/friends": {
      id: "/_authenticated/@me/friends"
      path: "/friends"
      fullPath: "/@me/friends"
      preLoaderRoute: typeof AuthenticatedAtmeFriendsRouteImport
      parentRoute: typeof AuthenticatedAtmeRouteRoute
    }
    "/_authenticated/spaces/$spaceId": {
      id: "/_authenticated/spaces/$spaceId"
      path: "/$spaceId"
      fullPath: "/spaces/$spaceId"
      preLoaderRoute: typeof AuthenticatedSpacesSpaceIdRouteRouteImport
      parentRoute: typeof AuthenticatedSpacesRouteRoute
    }
    "/_authenticated/@me/$channelId": {
      id: "/_authenticated/@me/$channelId"
      path: "/$channelId"
      fullPath: "/@me/$channelId"
      preLoaderRoute: typeof AuthenticatedAtmeChannelIdRouteRouteImport
      parentRoute: typeof AuthenticatedAtmeRouteRoute
    }
    "/_authenticated/feed/posts/$postId": {
      id: "/_authenticated/feed/posts/$postId"
      path: "/posts/$postId"
      fullPath: "/feed/posts/$postId"
      preLoaderRoute: typeof AuthenticatedFeedPostsPostIdRouteImport
      parentRoute: typeof AuthenticatedFeedRouteRoute
    }
    "/_authenticated/spaces/$spaceId/$channelId": {
      id: "/_authenticated/spaces/$spaceId/$channelId"
      path: "/$channelId"
      fullPath: "/spaces/$spaceId/$channelId"
      preLoaderRoute: typeof AuthenticatedSpacesSpaceIdChannelIdRouteRouteImport
      parentRoute: typeof AuthenticatedSpacesSpaceIdRouteRoute
    }
  }
}

interface AuthenticatedAtmeRouteRouteChildren {
  AuthenticatedAtmeChannelIdRouteRoute: typeof AuthenticatedAtmeChannelIdRouteRoute
  AuthenticatedAtmeFriendsRoute: typeof AuthenticatedAtmeFriendsRoute
}

const AuthenticatedAtmeRouteRouteChildren: AuthenticatedAtmeRouteRouteChildren =
  {
    AuthenticatedAtmeChannelIdRouteRoute: AuthenticatedAtmeChannelIdRouteRoute,
    AuthenticatedAtmeFriendsRoute: AuthenticatedAtmeFriendsRoute,
  }

const AuthenticatedAtmeRouteRouteWithChildren =
  AuthenticatedAtmeRouteRoute._addFileChildren(
    AuthenticatedAtmeRouteRouteChildren,
  )

interface AuthenticatedFeedRouteRouteChildren {
  AuthenticatedFeedFriendsRoute: typeof AuthenticatedFeedFriendsRoute
  AuthenticatedFeedSavedRoute: typeof AuthenticatedFeedSavedRoute
  AuthenticatedFeedScheduledRoute: typeof AuthenticatedFeedScheduledRoute
  AuthenticatedFeedIndexRoute: typeof AuthenticatedFeedIndexRoute
  AuthenticatedFeedPostsPostIdRoute: typeof AuthenticatedFeedPostsPostIdRoute
}

const AuthenticatedFeedRouteRouteChildren: AuthenticatedFeedRouteRouteChildren =
  {
    AuthenticatedFeedFriendsRoute: AuthenticatedFeedFriendsRoute,
    AuthenticatedFeedSavedRoute: AuthenticatedFeedSavedRoute,
    AuthenticatedFeedScheduledRoute: AuthenticatedFeedScheduledRoute,
    AuthenticatedFeedIndexRoute: AuthenticatedFeedIndexRoute,
    AuthenticatedFeedPostsPostIdRoute: AuthenticatedFeedPostsPostIdRoute,
  }

const AuthenticatedFeedRouteRouteWithChildren =
  AuthenticatedFeedRouteRoute._addFileChildren(
    AuthenticatedFeedRouteRouteChildren,
  )

interface AuthenticatedSpacesSpaceIdRouteRouteChildren {
  AuthenticatedSpacesSpaceIdChannelIdRouteRoute: typeof AuthenticatedSpacesSpaceIdChannelIdRouteRoute
}

const AuthenticatedSpacesSpaceIdRouteRouteChildren: AuthenticatedSpacesSpaceIdRouteRouteChildren =
  {
    AuthenticatedSpacesSpaceIdChannelIdRouteRoute:
      AuthenticatedSpacesSpaceIdChannelIdRouteRoute,
  }

const AuthenticatedSpacesSpaceIdRouteRouteWithChildren =
  AuthenticatedSpacesSpaceIdRouteRoute._addFileChildren(
    AuthenticatedSpacesSpaceIdRouteRouteChildren,
  )

interface AuthenticatedSpacesRouteRouteChildren {
  AuthenticatedSpacesSpaceIdRouteRoute: typeof AuthenticatedSpacesSpaceIdRouteRouteWithChildren
}

const AuthenticatedSpacesRouteRouteChildren: AuthenticatedSpacesRouteRouteChildren =
  {
    AuthenticatedSpacesSpaceIdRouteRoute:
      AuthenticatedSpacesSpaceIdRouteRouteWithChildren,
  }

const AuthenticatedSpacesRouteRouteWithChildren =
  AuthenticatedSpacesRouteRoute._addFileChildren(
    AuthenticatedSpacesRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtmeRouteRoute: typeof AuthenticatedAtmeRouteRouteWithChildren
  AuthenticatedAvatarRouteRoute: typeof AuthenticatedAvatarRouteRoute
  AuthenticatedFeedRouteRoute: typeof AuthenticatedFeedRouteRouteWithChildren
  AuthenticatedProfileRouteRoute: typeof AuthenticatedProfileRouteRoute
  AuthenticatedSpacesRouteRoute: typeof AuthenticatedSpacesRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtmeRouteRoute: AuthenticatedAtmeRouteRouteWithChildren,
  AuthenticatedAvatarRouteRoute: AuthenticatedAvatarRouteRoute,
  AuthenticatedFeedRouteRoute: AuthenticatedFeedRouteRouteWithChildren,
  AuthenticatedProfileRouteRoute: AuthenticatedProfileRouteRoute,
  AuthenticatedSpacesRouteRoute: AuthenticatedSpacesRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DownloadRoute: DownloadRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetRoute: ResetRoute,
  UsersUsernameRouteRoute: UsersUsernameRouteRoute,
  InviteCodeRoute: InviteCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
