/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as TosRouteImport } from "./routes/tos"
import { Route as SupportRouteImport } from "./routes/support"
import { Route as ResetRouteImport } from "./routes/reset"
import { Route as RegisterRouteImport } from "./routes/register"
import { Route as PrivacyRouteImport } from "./routes/privacy"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as DownloadRouteImport } from "./routes/download"
import { Route as AppealRouteImport } from "./routes/appeal"
import { Route as AuthenticatedRouteRouteImport } from "./routes/_authenticated/route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as SpotifyCallbackRouteImport } from "./routes/spotify/callback"
import { Route as InviteCodeRouteImport } from "./routes/invite/$code"
import { Route as ConnectionsCallbackRouteImport } from "./routes/connections/callback"
import { Route as UsersUsernameRouteRouteImport } from "./routes/users/$username/route"
import { Route as AuthenticatedStaffRouteRouteImport } from "./routes/_authenticated/staff/route"
import { Route as AuthenticatedSpacesRouteRouteImport } from "./routes/_authenticated/spaces/route"
import { Route as AuthenticatedProfileRouteRouteImport } from "./routes/_authenticated/profile/route"
import { Route as AuthenticatedFeedRouteRouteImport } from "./routes/_authenticated/feed/route"
import { Route as AuthenticatedAvatarRouteRouteImport } from "./routes/_authenticated/avatar/route"
import { Route as AuthenticatedAtmeRouteRouteImport } from "./routes/_authenticated/@me/route"
import { Route as AuthenticatedStaffIndexRouteImport } from "./routes/_authenticated/staff/index"
import { Route as AuthenticatedFeedIndexRouteImport } from "./routes/_authenticated/feed/index"
import { Route as AuthenticatedStaffSupportRouteImport } from "./routes/_authenticated/staff/support"
import { Route as AuthenticatedStaffChangelogsRouteImport } from "./routes/_authenticated/staff/changelogs"
import { Route as AuthenticatedStaffAppealsRouteImport } from "./routes/_authenticated/staff/appeals"
import { Route as AuthenticatedStaffActivityRouteImport } from "./routes/_authenticated/staff/activity"
import { Route as AuthenticatedFeedScheduledRouteImport } from "./routes/_authenticated/feed/scheduled"
import { Route as AuthenticatedFeedSavedRouteImport } from "./routes/_authenticated/feed/saved"
import { Route as AuthenticatedFeedFriendsRouteImport } from "./routes/_authenticated/feed/friends"
import { Route as AuthenticatedAtmeFriendsRouteImport } from "./routes/_authenticated/@me/friends"
import { Route as AuthenticatedSpacesSpaceIdRouteRouteImport } from "./routes/_authenticated/spaces/$spaceId/route"
import { Route as AuthenticatedAtmeChannelIdRouteRouteImport } from "./routes/_authenticated/@me/$channelId/route"
import { Route as AuthenticatedSupportTicketsIndexRouteImport } from "./routes/_authenticated/support/tickets/index"
import { Route as AuthenticatedStaffReportsIndexRouteImport } from "./routes/_authenticated/staff/reports/index"
import { Route as AuthenticatedAtmeBridgesIndexRouteImport } from "./routes/_authenticated/@me/bridges/index"
import { Route as AuthenticatedSupportTicketsTicketIdRouteImport } from "./routes/_authenticated/support/tickets/$ticketId"
import { Route as AuthenticatedStaffReportsReportIdRouteImport } from "./routes/_authenticated/staff/reports/$reportId"
import { Route as AuthenticatedFeedPostsPostIdRouteImport } from "./routes/_authenticated/feed/posts/$postId"
import { Route as AuthenticatedAtmeBridgesBridgeIdRouteImport } from "./routes/_authenticated/@me/bridges/$bridgeId"
import { Route as AuthenticatedStaffUsersUserIdRouteRouteImport } from "./routes/_authenticated/staff/users/$userId/route"
import { Route as AuthenticatedSpacesSpaceIdChannelIdRouteRouteImport } from "./routes/_authenticated/spaces/$spaceId/$channelId/route"
import { Route as AuthenticatedSpacesSpaceIdBridgesBridgeIdRouteImport } from "./routes/_authenticated/spaces/$spaceId/bridges/$bridgeId"

const TosRoute = TosRouteImport.update({
  id: "/tos",
  path: "/tos",
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: "/support",
  path: "/support",
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: "/reset",
  path: "/reset",
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: "/privacy",
  path: "/privacy",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: "/download",
  path: "/download",
  getParentRoute: () => rootRouteImport,
} as any)
const AppealRoute = AppealRouteImport.update({
  id: "/appeal",
  path: "/appeal",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const SpotifyCallbackRoute = SpotifyCallbackRouteImport.update({
  id: "/spotify/callback",
  path: "/spotify/callback",
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: "/invite/$code",
  path: "/invite/$code",
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsCallbackRoute = ConnectionsCallbackRouteImport.update({
  id: "/connections/callback",
  path: "/connections/callback",
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUsernameRouteRoute = UsersUsernameRouteRouteImport.update({
  id: "/users/$username",
  path: "/users/$username",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStaffRouteRoute = AuthenticatedStaffRouteRouteImport.update({
  id: "/staff",
  path: "/staff",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSpacesRouteRoute =
  AuthenticatedSpacesRouteRouteImport.update({
    id: "/spaces",
    path: "/spaces",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRouteRoute =
  AuthenticatedProfileRouteRouteImport.update({
    id: "/profile",
    path: "/profile",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeedRouteRoute = AuthenticatedFeedRouteRouteImport.update({
  id: "/feed",
  path: "/feed",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvatarRouteRoute =
  AuthenticatedAvatarRouteRouteImport.update({
    id: "/avatar",
    path: "/avatar",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAtmeRouteRoute = AuthenticatedAtmeRouteRouteImport.update({
  id: "/@me",
  path: "/@me",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthenticatedStaffRouteRoute,
} as any)
const AuthenticatedFeedIndexRoute = AuthenticatedFeedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthenticatedFeedRouteRoute,
} as any)
const AuthenticatedStaffSupportRoute =
  AuthenticatedStaffSupportRouteImport.update({
    id: "/support",
    path: "/support",
    getParentRoute: () => AuthenticatedStaffRouteRoute,
  } as any)
const AuthenticatedStaffChangelogsRoute =
  AuthenticatedStaffChangelogsRouteImport.update({
    id: "/changelogs",
    path: "/changelogs",
    getParentRoute: () => AuthenticatedStaffRouteRoute,
  } as any)
const AuthenticatedStaffAppealsRoute =
  AuthenticatedStaffAppealsRouteImport.update({
    id: "/appeals",
    path: "/appeals",
    getParentRoute: () => AuthenticatedStaffRouteRoute,
  } as any)
const AuthenticatedStaffActivityRoute =
  AuthenticatedStaffActivityRouteImport.update({
    id: "/activity",
    path: "/activity",
    getParentRoute: () => AuthenticatedStaffRouteRoute,
  } as any)
const AuthenticatedFeedScheduledRoute =
  AuthenticatedFeedScheduledRouteImport.update({
    id: "/scheduled",
    path: "/scheduled",
    getParentRoute: () => AuthenticatedFeedRouteRoute,
  } as any)
const AuthenticatedFeedSavedRoute = AuthenticatedFeedSavedRouteImport.update({
  id: "/saved",
  path: "/saved",
  getParentRoute: () => AuthenticatedFeedRouteRoute,
} as any)
const AuthenticatedFeedFriendsRoute =
  AuthenticatedFeedFriendsRouteImport.update({
    id: "/friends",
    path: "/friends",
    getParentRoute: () => AuthenticatedFeedRouteRoute,
  } as any)
const AuthenticatedAtmeFriendsRoute =
  AuthenticatedAtmeFriendsRouteImport.update({
    id: "/friends",
    path: "/friends",
    getParentRoute: () => AuthenticatedAtmeRouteRoute,
  } as any)
const AuthenticatedSpacesSpaceIdRouteRoute =
  AuthenticatedSpacesSpaceIdRouteRouteImport.update({
    id: "/$spaceId",
    path: "/$spaceId",
    getParentRoute: () => AuthenticatedSpacesRouteRoute,
  } as any)
const AuthenticatedAtmeChannelIdRouteRoute =
  AuthenticatedAtmeChannelIdRouteRouteImport.update({
    id: "/$channelId",
    path: "/$channelId",
    getParentRoute: () => AuthenticatedAtmeRouteRoute,
  } as any)
const AuthenticatedSupportTicketsIndexRoute =
  AuthenticatedSupportTicketsIndexRouteImport.update({
    id: "/support/tickets/",
    path: "/support/tickets/",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffReportsIndexRoute =
  AuthenticatedStaffReportsIndexRouteImport.update({
    id: "/reports/",
    path: "/reports/",
    getParentRoute: () => AuthenticatedStaffRouteRoute,
  } as any)
const AuthenticatedAtmeBridgesIndexRoute =
  AuthenticatedAtmeBridgesIndexRouteImport.update({
    id: "/bridges/",
    path: "/bridges/",
    getParentRoute: () => AuthenticatedAtmeRouteRoute,
  } as any)
const AuthenticatedSupportTicketsTicketIdRoute =
  AuthenticatedSupportTicketsTicketIdRouteImport.update({
    id: "/support/tickets/$ticketId",
    path: "/support/tickets/$ticketId",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffReportsReportIdRoute =
  AuthenticatedStaffReportsReportIdRouteImport.update({
    id: "/reports/$reportId",
    path: "/reports/$reportId",
    getParentRoute: () => AuthenticatedStaffRouteRoute,
  } as any)
const AuthenticatedFeedPostsPostIdRoute =
  AuthenticatedFeedPostsPostIdRouteImport.update({
    id: "/posts/$postId",
    path: "/posts/$postId",
    getParentRoute: () => AuthenticatedFeedRouteRoute,
  } as any)
const AuthenticatedAtmeBridgesBridgeIdRoute =
  AuthenticatedAtmeBridgesBridgeIdRouteImport.update({
    id: "/bridges/$bridgeId",
    path: "/bridges/$bridgeId",
    getParentRoute: () => AuthenticatedAtmeRouteRoute,
  } as any)
const AuthenticatedStaffUsersUserIdRouteRoute =
  AuthenticatedStaffUsersUserIdRouteRouteImport.update({
    id: "/users/$userId",
    path: "/users/$userId",
    getParentRoute: () => AuthenticatedStaffRouteRoute,
  } as any)
const AuthenticatedSpacesSpaceIdChannelIdRouteRoute =
  AuthenticatedSpacesSpaceIdChannelIdRouteRouteImport.update({
    id: "/$channelId",
    path: "/$channelId",
    getParentRoute: () => AuthenticatedSpacesSpaceIdRouteRoute,
  } as any)
const AuthenticatedSpacesSpaceIdBridgesBridgeIdRoute =
  AuthenticatedSpacesSpaceIdBridgesBridgeIdRouteImport.update({
    id: "/bridges/$bridgeId",
    path: "/bridges/$bridgeId",
    getParentRoute: () => AuthenticatedSpacesSpaceIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/appeal": typeof AppealRoute
  "/download": typeof DownloadRoute
  "/login": typeof LoginRoute
  "/privacy": typeof PrivacyRoute
  "/register": typeof RegisterRoute
  "/reset": typeof ResetRoute
  "/support": typeof SupportRoute
  "/tos": typeof TosRoute
  "/@me": typeof AuthenticatedAtmeRouteRouteWithChildren
  "/avatar": typeof AuthenticatedAvatarRouteRoute
  "/feed": typeof AuthenticatedFeedRouteRouteWithChildren
  "/profile": typeof AuthenticatedProfileRouteRoute
  "/spaces": typeof AuthenticatedSpacesRouteRouteWithChildren
  "/staff": typeof AuthenticatedStaffRouteRouteWithChildren
  "/users/$username": typeof UsersUsernameRouteRoute
  "/connections/callback": typeof ConnectionsCallbackRoute
  "/invite/$code": typeof InviteCodeRoute
  "/spotify/callback": typeof SpotifyCallbackRoute
  "/@me/$channelId": typeof AuthenticatedAtmeChannelIdRouteRoute
  "/spaces/$spaceId": typeof AuthenticatedSpacesSpaceIdRouteRouteWithChildren
  "/@me/friends": typeof AuthenticatedAtmeFriendsRoute
  "/feed/friends": typeof AuthenticatedFeedFriendsRoute
  "/feed/saved": typeof AuthenticatedFeedSavedRoute
  "/feed/scheduled": typeof AuthenticatedFeedScheduledRoute
  "/staff/activity": typeof AuthenticatedStaffActivityRoute
  "/staff/appeals": typeof AuthenticatedStaffAppealsRoute
  "/staff/changelogs": typeof AuthenticatedStaffChangelogsRoute
  "/staff/support": typeof AuthenticatedStaffSupportRoute
  "/feed/": typeof AuthenticatedFeedIndexRoute
  "/staff/": typeof AuthenticatedStaffIndexRoute
  "/spaces/$spaceId/$channelId": typeof AuthenticatedSpacesSpaceIdChannelIdRouteRoute
  "/staff/users/$userId": typeof AuthenticatedStaffUsersUserIdRouteRoute
  "/@me/bridges/$bridgeId": typeof AuthenticatedAtmeBridgesBridgeIdRoute
  "/feed/posts/$postId": typeof AuthenticatedFeedPostsPostIdRoute
  "/staff/reports/$reportId": typeof AuthenticatedStaffReportsReportIdRoute
  "/support/tickets/$ticketId": typeof AuthenticatedSupportTicketsTicketIdRoute
  "/@me/bridges/": typeof AuthenticatedAtmeBridgesIndexRoute
  "/staff/reports/": typeof AuthenticatedStaffReportsIndexRoute
  "/support/tickets/": typeof AuthenticatedSupportTicketsIndexRoute
  "/spaces/$spaceId/bridges/$bridgeId": typeof AuthenticatedSpacesSpaceIdBridgesBridgeIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/appeal": typeof AppealRoute
  "/download": typeof DownloadRoute
  "/login": typeof LoginRoute
  "/privacy": typeof PrivacyRoute
  "/register": typeof RegisterRoute
  "/reset": typeof ResetRoute
  "/support": typeof SupportRoute
  "/tos": typeof TosRoute
  "/@me": typeof AuthenticatedAtmeRouteRouteWithChildren
  "/avatar": typeof AuthenticatedAvatarRouteRoute
  "/profile": typeof AuthenticatedProfileRouteRoute
  "/spaces": typeof AuthenticatedSpacesRouteRouteWithChildren
  "/users/$username": typeof UsersUsernameRouteRoute
  "/connections/callback": typeof ConnectionsCallbackRoute
  "/invite/$code": typeof InviteCodeRoute
  "/spotify/callback": typeof SpotifyCallbackRoute
  "/@me/$channelId": typeof AuthenticatedAtmeChannelIdRouteRoute
  "/spaces/$spaceId": typeof AuthenticatedSpacesSpaceIdRouteRouteWithChildren
  "/@me/friends": typeof AuthenticatedAtmeFriendsRoute
  "/feed/friends": typeof AuthenticatedFeedFriendsRoute
  "/feed/saved": typeof AuthenticatedFeedSavedRoute
  "/feed/scheduled": typeof AuthenticatedFeedScheduledRoute
  "/staff/activity": typeof AuthenticatedStaffActivityRoute
  "/staff/appeals": typeof AuthenticatedStaffAppealsRoute
  "/staff/changelogs": typeof AuthenticatedStaffChangelogsRoute
  "/staff/support": typeof AuthenticatedStaffSupportRoute
  "/feed": typeof AuthenticatedFeedIndexRoute
  "/staff": typeof AuthenticatedStaffIndexRoute
  "/spaces/$spaceId/$channelId": typeof AuthenticatedSpacesSpaceIdChannelIdRouteRoute
  "/staff/users/$userId": typeof AuthenticatedStaffUsersUserIdRouteRoute
  "/@me/bridges/$bridgeId": typeof AuthenticatedAtmeBridgesBridgeIdRoute
  "/feed/posts/$postId": typeof AuthenticatedFeedPostsPostIdRoute
  "/staff/reports/$reportId": typeof AuthenticatedStaffReportsReportIdRoute
  "/support/tickets/$ticketId": typeof AuthenticatedSupportTicketsTicketIdRoute
  "/@me/bridges": typeof AuthenticatedAtmeBridgesIndexRoute
  "/staff/reports": typeof AuthenticatedStaffReportsIndexRoute
  "/support/tickets": typeof AuthenticatedSupportTicketsIndexRoute
  "/spaces/$spaceId/bridges/$bridgeId": typeof AuthenticatedSpacesSpaceIdBridgesBridgeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_authenticated": typeof AuthenticatedRouteRouteWithChildren
  "/appeal": typeof AppealRoute
  "/download": typeof DownloadRoute
  "/login": typeof LoginRoute
  "/privacy": typeof PrivacyRoute
  "/register": typeof RegisterRoute
  "/reset": typeof ResetRoute
  "/support": typeof SupportRoute
  "/tos": typeof TosRoute
  "/_authenticated/@me": typeof AuthenticatedAtmeRouteRouteWithChildren
  "/_authenticated/avatar": typeof AuthenticatedAvatarRouteRoute
  "/_authenticated/feed": typeof AuthenticatedFeedRouteRouteWithChildren
  "/_authenticated/profile": typeof AuthenticatedProfileRouteRoute
  "/_authenticated/spaces": typeof AuthenticatedSpacesRouteRouteWithChildren
  "/_authenticated/staff": typeof AuthenticatedStaffRouteRouteWithChildren
  "/users/$username": typeof UsersUsernameRouteRoute
  "/connections/callback": typeof ConnectionsCallbackRoute
  "/invite/$code": typeof InviteCodeRoute
  "/spotify/callback": typeof SpotifyCallbackRoute
  "/_authenticated/@me/$channelId": typeof AuthenticatedAtmeChannelIdRouteRoute
  "/_authenticated/spaces/$spaceId": typeof AuthenticatedSpacesSpaceIdRouteRouteWithChildren
  "/_authenticated/@me/friends": typeof AuthenticatedAtmeFriendsRoute
  "/_authenticated/feed/friends": typeof AuthenticatedFeedFriendsRoute
  "/_authenticated/feed/saved": typeof AuthenticatedFeedSavedRoute
  "/_authenticated/feed/scheduled": typeof AuthenticatedFeedScheduledRoute
  "/_authenticated/staff/activity": typeof AuthenticatedStaffActivityRoute
  "/_authenticated/staff/appeals": typeof AuthenticatedStaffAppealsRoute
  "/_authenticated/staff/changelogs": typeof AuthenticatedStaffChangelogsRoute
  "/_authenticated/staff/support": typeof AuthenticatedStaffSupportRoute
  "/_authenticated/feed/": typeof AuthenticatedFeedIndexRoute
  "/_authenticated/staff/": typeof AuthenticatedStaffIndexRoute
  "/_authenticated/spaces/$spaceId/$channelId": typeof AuthenticatedSpacesSpaceIdChannelIdRouteRoute
  "/_authenticated/staff/users/$userId": typeof AuthenticatedStaffUsersUserIdRouteRoute
  "/_authenticated/@me/bridges/$bridgeId": typeof AuthenticatedAtmeBridgesBridgeIdRoute
  "/_authenticated/feed/posts/$postId": typeof AuthenticatedFeedPostsPostIdRoute
  "/_authenticated/staff/reports/$reportId": typeof AuthenticatedStaffReportsReportIdRoute
  "/_authenticated/support/tickets/$ticketId": typeof AuthenticatedSupportTicketsTicketIdRoute
  "/_authenticated/@me/bridges/": typeof AuthenticatedAtmeBridgesIndexRoute
  "/_authenticated/staff/reports/": typeof AuthenticatedStaffReportsIndexRoute
  "/_authenticated/support/tickets/": typeof AuthenticatedSupportTicketsIndexRoute
  "/_authenticated/spaces/$spaceId/bridges/$bridgeId": typeof AuthenticatedSpacesSpaceIdBridgesBridgeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/appeal"
    | "/download"
    | "/login"
    | "/privacy"
    | "/register"
    | "/reset"
    | "/support"
    | "/tos"
    | "/@me"
    | "/avatar"
    | "/feed"
    | "/profile"
    | "/spaces"
    | "/staff"
    | "/users/$username"
    | "/connections/callback"
    | "/invite/$code"
    | "/spotify/callback"
    | "/@me/$channelId"
    | "/spaces/$spaceId"
    | "/@me/friends"
    | "/feed/friends"
    | "/feed/saved"
    | "/feed/scheduled"
    | "/staff/activity"
    | "/staff/appeals"
    | "/staff/changelogs"
    | "/staff/support"
    | "/feed/"
    | "/staff/"
    | "/spaces/$spaceId/$channelId"
    | "/staff/users/$userId"
    | "/@me/bridges/$bridgeId"
    | "/feed/posts/$postId"
    | "/staff/reports/$reportId"
    | "/support/tickets/$ticketId"
    | "/@me/bridges/"
    | "/staff/reports/"
    | "/support/tickets/"
    | "/spaces/$spaceId/bridges/$bridgeId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/appeal"
    | "/download"
    | "/login"
    | "/privacy"
    | "/register"
    | "/reset"
    | "/support"
    | "/tos"
    | "/@me"
    | "/avatar"
    | "/profile"
    | "/spaces"
    | "/users/$username"
    | "/connections/callback"
    | "/invite/$code"
    | "/spotify/callback"
    | "/@me/$channelId"
    | "/spaces/$spaceId"
    | "/@me/friends"
    | "/feed/friends"
    | "/feed/saved"
    | "/feed/scheduled"
    | "/staff/activity"
    | "/staff/appeals"
    | "/staff/changelogs"
    | "/staff/support"
    | "/feed"
    | "/staff"
    | "/spaces/$spaceId/$channelId"
    | "/staff/users/$userId"
    | "/@me/bridges/$bridgeId"
    | "/feed/posts/$postId"
    | "/staff/reports/$reportId"
    | "/support/tickets/$ticketId"
    | "/@me/bridges"
    | "/staff/reports"
    | "/support/tickets"
    | "/spaces/$spaceId/bridges/$bridgeId"
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/appeal"
    | "/download"
    | "/login"
    | "/privacy"
    | "/register"
    | "/reset"
    | "/support"
    | "/tos"
    | "/_authenticated/@me"
    | "/_authenticated/avatar"
    | "/_authenticated/feed"
    | "/_authenticated/profile"
    | "/_authenticated/spaces"
    | "/_authenticated/staff"
    | "/users/$username"
    | "/connections/callback"
    | "/invite/$code"
    | "/spotify/callback"
    | "/_authenticated/@me/$channelId"
    | "/_authenticated/spaces/$spaceId"
    | "/_authenticated/@me/friends"
    | "/_authenticated/feed/friends"
    | "/_authenticated/feed/saved"
    | "/_authenticated/feed/scheduled"
    | "/_authenticated/staff/activity"
    | "/_authenticated/staff/appeals"
    | "/_authenticated/staff/changelogs"
    | "/_authenticated/staff/support"
    | "/_authenticated/feed/"
    | "/_authenticated/staff/"
    | "/_authenticated/spaces/$spaceId/$channelId"
    | "/_authenticated/staff/users/$userId"
    | "/_authenticated/@me/bridges/$bridgeId"
    | "/_authenticated/feed/posts/$postId"
    | "/_authenticated/staff/reports/$reportId"
    | "/_authenticated/support/tickets/$ticketId"
    | "/_authenticated/@me/bridges/"
    | "/_authenticated/staff/reports/"
    | "/_authenticated/support/tickets/"
    | "/_authenticated/spaces/$spaceId/bridges/$bridgeId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AppealRoute: typeof AppealRoute
  DownloadRoute: typeof DownloadRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetRoute: typeof ResetRoute
  SupportRoute: typeof SupportRoute
  TosRoute: typeof TosRoute
  UsersUsernameRouteRoute: typeof UsersUsernameRouteRoute
  ConnectionsCallbackRoute: typeof ConnectionsCallbackRoute
  InviteCodeRoute: typeof InviteCodeRoute
  SpotifyCallbackRoute: typeof SpotifyCallbackRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/tos": {
      id: "/tos"
      path: "/tos"
      fullPath: "/tos"
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/support": {
      id: "/support"
      path: "/support"
      fullPath: "/support"
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reset": {
      id: "/reset"
      path: "/reset"
      fullPath: "/reset"
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/register": {
      id: "/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/privacy": {
      id: "/privacy"
      path: "/privacy"
      fullPath: "/privacy"
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/download": {
      id: "/download"
      path: "/download"
      fullPath: "/download"
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/appeal": {
      id: "/appeal"
      path: "/appeal"
      fullPath: "/appeal"
      preLoaderRoute: typeof AppealRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated": {
      id: "/_authenticated"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/spotify/callback": {
      id: "/spotify/callback"
      path: "/spotify/callback"
      fullPath: "/spotify/callback"
      preLoaderRoute: typeof SpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/invite/$code": {
      id: "/invite/$code"
      path: "/invite/$code"
      fullPath: "/invite/$code"
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/connections/callback": {
      id: "/connections/callback"
      path: "/connections/callback"
      fullPath: "/connections/callback"
      preLoaderRoute: typeof ConnectionsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/users/$username": {
      id: "/users/$username"
      path: "/users/$username"
      fullPath: "/users/$username"
      preLoaderRoute: typeof UsersUsernameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated/staff": {
      id: "/_authenticated/staff"
      path: "/staff"
      fullPath: "/staff"
      preLoaderRoute: typeof AuthenticatedStaffRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/spaces": {
      id: "/_authenticated/spaces"
      path: "/spaces"
      fullPath: "/spaces"
      preLoaderRoute: typeof AuthenticatedSpacesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/profile": {
      id: "/_authenticated/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof AuthenticatedProfileRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/feed": {
      id: "/_authenticated/feed"
      path: "/feed"
      fullPath: "/feed"
      preLoaderRoute: typeof AuthenticatedFeedRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/avatar": {
      id: "/_authenticated/avatar"
      path: "/avatar"
      fullPath: "/avatar"
      preLoaderRoute: typeof AuthenticatedAvatarRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/@me": {
      id: "/_authenticated/@me"
      path: "/@me"
      fullPath: "/@me"
      preLoaderRoute: typeof AuthenticatedAtmeRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/staff/": {
      id: "/_authenticated/staff/"
      path: "/"
      fullPath: "/staff/"
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedStaffRouteRoute
    }
    "/_authenticated/feed/": {
      id: "/_authenticated/feed/"
      path: "/"
      fullPath: "/feed/"
      preLoaderRoute: typeof AuthenticatedFeedIndexRouteImport
      parentRoute: typeof AuthenticatedFeedRouteRoute
    }
    "/_authenticated/staff/support": {
      id: "/_authenticated/staff/support"
      path: "/support"
      fullPath: "/staff/support"
      preLoaderRoute: typeof AuthenticatedStaffSupportRouteImport
      parentRoute: typeof AuthenticatedStaffRouteRoute
    }
    "/_authenticated/staff/changelogs": {
      id: "/_authenticated/staff/changelogs"
      path: "/changelogs"
      fullPath: "/staff/changelogs"
      preLoaderRoute: typeof AuthenticatedStaffChangelogsRouteImport
      parentRoute: typeof AuthenticatedStaffRouteRoute
    }
    "/_authenticated/staff/appeals": {
      id: "/_authenticated/staff/appeals"
      path: "/appeals"
      fullPath: "/staff/appeals"
      preLoaderRoute: typeof AuthenticatedStaffAppealsRouteImport
      parentRoute: typeof AuthenticatedStaffRouteRoute
    }
    "/_authenticated/staff/activity": {
      id: "/_authenticated/staff/activity"
      path: "/activity"
      fullPath: "/staff/activity"
      preLoaderRoute: typeof AuthenticatedStaffActivityRouteImport
      parentRoute: typeof AuthenticatedStaffRouteRoute
    }
    "/_authenticated/feed/scheduled": {
      id: "/_authenticated/feed/scheduled"
      path: "/scheduled"
      fullPath: "/feed/scheduled"
      preLoaderRoute: typeof AuthenticatedFeedScheduledRouteImport
      parentRoute: typeof AuthenticatedFeedRouteRoute
    }
    "/_authenticated/feed/saved": {
      id: "/_authenticated/feed/saved"
      path: "/saved"
      fullPath: "/feed/saved"
      preLoaderRoute: typeof AuthenticatedFeedSavedRouteImport
      parentRoute: typeof AuthenticatedFeedRouteRoute
    }
    "/_authenticated/feed/friends": {
      id: "/_authenticated/feed/friends"
      path: "/friends"
      fullPath: "/feed/friends"
      preLoaderRoute: typeof AuthenticatedFeedFriendsRouteImport
      parentRoute: typeof AuthenticatedFeedRouteRoute
    }
    "/_authenticated/@me/friends": {
      id: "/_authenticated/@me/friends"
      path: "/friends"
      fullPath: "/@me/friends"
      preLoaderRoute: typeof AuthenticatedAtmeFriendsRouteImport
      parentRoute: typeof AuthenticatedAtmeRouteRoute
    }
    "/_authenticated/spaces/$spaceId": {
      id: "/_authenticated/spaces/$spaceId"
      path: "/$spaceId"
      fullPath: "/spaces/$spaceId"
      preLoaderRoute: typeof AuthenticatedSpacesSpaceIdRouteRouteImport
      parentRoute: typeof AuthenticatedSpacesRouteRoute
    }
    "/_authenticated/@me/$channelId": {
      id: "/_authenticated/@me/$channelId"
      path: "/$channelId"
      fullPath: "/@me/$channelId"
      preLoaderRoute: typeof AuthenticatedAtmeChannelIdRouteRouteImport
      parentRoute: typeof AuthenticatedAtmeRouteRoute
    }
    "/_authenticated/support/tickets/": {
      id: "/_authenticated/support/tickets/"
      path: "/support/tickets"
      fullPath: "/support/tickets/"
      preLoaderRoute: typeof AuthenticatedSupportTicketsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/staff/reports/": {
      id: "/_authenticated/staff/reports/"
      path: "/reports"
      fullPath: "/staff/reports/"
      preLoaderRoute: typeof AuthenticatedStaffReportsIndexRouteImport
      parentRoute: typeof AuthenticatedStaffRouteRoute
    }
    "/_authenticated/@me/bridges/": {
      id: "/_authenticated/@me/bridges/"
      path: "/bridges"
      fullPath: "/@me/bridges/"
      preLoaderRoute: typeof AuthenticatedAtmeBridgesIndexRouteImport
      parentRoute: typeof AuthenticatedAtmeRouteRoute
    }
    "/_authenticated/support/tickets/$ticketId": {
      id: "/_authenticated/support/tickets/$ticketId"
      path: "/support/tickets/$ticketId"
      fullPath: "/support/tickets/$ticketId"
      preLoaderRoute: typeof AuthenticatedSupportTicketsTicketIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    "/_authenticated/staff/reports/$reportId": {
      id: "/_authenticated/staff/reports/$reportId"
      path: "/reports/$reportId"
      fullPath: "/staff/reports/$reportId"
      preLoaderRoute: typeof AuthenticatedStaffReportsReportIdRouteImport
      parentRoute: typeof AuthenticatedStaffRouteRoute
    }
    "/_authenticated/feed/posts/$postId": {
      id: "/_authenticated/feed/posts/$postId"
      path: "/posts/$postId"
      fullPath: "/feed/posts/$postId"
      preLoaderRoute: typeof AuthenticatedFeedPostsPostIdRouteImport
      parentRoute: typeof AuthenticatedFeedRouteRoute
    }
    "/_authenticated/@me/bridges/$bridgeId": {
      id: "/_authenticated/@me/bridges/$bridgeId"
      path: "/bridges/$bridgeId"
      fullPath: "/@me/bridges/$bridgeId"
      preLoaderRoute: typeof AuthenticatedAtmeBridgesBridgeIdRouteImport
      parentRoute: typeof AuthenticatedAtmeRouteRoute
    }
    "/_authenticated/staff/users/$userId": {
      id: "/_authenticated/staff/users/$userId"
      path: "/users/$userId"
      fullPath: "/staff/users/$userId"
      preLoaderRoute: typeof AuthenticatedStaffUsersUserIdRouteRouteImport
      parentRoute: typeof AuthenticatedStaffRouteRoute
    }
    "/_authenticated/spaces/$spaceId/$channelId": {
      id: "/_authenticated/spaces/$spaceId/$channelId"
      path: "/$channelId"
      fullPath: "/spaces/$spaceId/$channelId"
      preLoaderRoute: typeof AuthenticatedSpacesSpaceIdChannelIdRouteRouteImport
      parentRoute: typeof AuthenticatedSpacesSpaceIdRouteRoute
    }
    "/_authenticated/spaces/$spaceId/bridges/$bridgeId": {
      id: "/_authenticated/spaces/$spaceId/bridges/$bridgeId"
      path: "/bridges/$bridgeId"
      fullPath: "/spaces/$spaceId/bridges/$bridgeId"
      preLoaderRoute: typeof AuthenticatedSpacesSpaceIdBridgesBridgeIdRouteImport
      parentRoute: typeof AuthenticatedSpacesSpaceIdRouteRoute
    }
  }
}

interface AuthenticatedAtmeRouteRouteChildren {
  AuthenticatedAtmeChannelIdRouteRoute: typeof AuthenticatedAtmeChannelIdRouteRoute
  AuthenticatedAtmeFriendsRoute: typeof AuthenticatedAtmeFriendsRoute
  AuthenticatedAtmeBridgesBridgeIdRoute: typeof AuthenticatedAtmeBridgesBridgeIdRoute
  AuthenticatedAtmeBridgesIndexRoute: typeof AuthenticatedAtmeBridgesIndexRoute
}

const AuthenticatedAtmeRouteRouteChildren: AuthenticatedAtmeRouteRouteChildren =
  {
    AuthenticatedAtmeChannelIdRouteRoute: AuthenticatedAtmeChannelIdRouteRoute,
    AuthenticatedAtmeFriendsRoute: AuthenticatedAtmeFriendsRoute,
    AuthenticatedAtmeBridgesBridgeIdRoute:
      AuthenticatedAtmeBridgesBridgeIdRoute,
    AuthenticatedAtmeBridgesIndexRoute: AuthenticatedAtmeBridgesIndexRoute,
  }

const AuthenticatedAtmeRouteRouteWithChildren =
  AuthenticatedAtmeRouteRoute._addFileChildren(
    AuthenticatedAtmeRouteRouteChildren,
  )

interface AuthenticatedFeedRouteRouteChildren {
  AuthenticatedFeedFriendsRoute: typeof AuthenticatedFeedFriendsRoute
  AuthenticatedFeedSavedRoute: typeof AuthenticatedFeedSavedRoute
  AuthenticatedFeedScheduledRoute: typeof AuthenticatedFeedScheduledRoute
  AuthenticatedFeedIndexRoute: typeof AuthenticatedFeedIndexRoute
  AuthenticatedFeedPostsPostIdRoute: typeof AuthenticatedFeedPostsPostIdRoute
}

const AuthenticatedFeedRouteRouteChildren: AuthenticatedFeedRouteRouteChildren =
  {
    AuthenticatedFeedFriendsRoute: AuthenticatedFeedFriendsRoute,
    AuthenticatedFeedSavedRoute: AuthenticatedFeedSavedRoute,
    AuthenticatedFeedScheduledRoute: AuthenticatedFeedScheduledRoute,
    AuthenticatedFeedIndexRoute: AuthenticatedFeedIndexRoute,
    AuthenticatedFeedPostsPostIdRoute: AuthenticatedFeedPostsPostIdRoute,
  }

const AuthenticatedFeedRouteRouteWithChildren =
  AuthenticatedFeedRouteRoute._addFileChildren(
    AuthenticatedFeedRouteRouteChildren,
  )

interface AuthenticatedSpacesSpaceIdRouteRouteChildren {
  AuthenticatedSpacesSpaceIdChannelIdRouteRoute: typeof AuthenticatedSpacesSpaceIdChannelIdRouteRoute
  AuthenticatedSpacesSpaceIdBridgesBridgeIdRoute: typeof AuthenticatedSpacesSpaceIdBridgesBridgeIdRoute
}

const AuthenticatedSpacesSpaceIdRouteRouteChildren: AuthenticatedSpacesSpaceIdRouteRouteChildren =
  {
    AuthenticatedSpacesSpaceIdChannelIdRouteRoute:
      AuthenticatedSpacesSpaceIdChannelIdRouteRoute,
    AuthenticatedSpacesSpaceIdBridgesBridgeIdRoute:
      AuthenticatedSpacesSpaceIdBridgesBridgeIdRoute,
  }

const AuthenticatedSpacesSpaceIdRouteRouteWithChildren =
  AuthenticatedSpacesSpaceIdRouteRoute._addFileChildren(
    AuthenticatedSpacesSpaceIdRouteRouteChildren,
  )

interface AuthenticatedSpacesRouteRouteChildren {
  AuthenticatedSpacesSpaceIdRouteRoute: typeof AuthenticatedSpacesSpaceIdRouteRouteWithChildren
}

const AuthenticatedSpacesRouteRouteChildren: AuthenticatedSpacesRouteRouteChildren =
  {
    AuthenticatedSpacesSpaceIdRouteRoute:
      AuthenticatedSpacesSpaceIdRouteRouteWithChildren,
  }

const AuthenticatedSpacesRouteRouteWithChildren =
  AuthenticatedSpacesRouteRoute._addFileChildren(
    AuthenticatedSpacesRouteRouteChildren,
  )

interface AuthenticatedStaffRouteRouteChildren {
  AuthenticatedStaffActivityRoute: typeof AuthenticatedStaffActivityRoute
  AuthenticatedStaffAppealsRoute: typeof AuthenticatedStaffAppealsRoute
  AuthenticatedStaffChangelogsRoute: typeof AuthenticatedStaffChangelogsRoute
  AuthenticatedStaffSupportRoute: typeof AuthenticatedStaffSupportRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
  AuthenticatedStaffUsersUserIdRouteRoute: typeof AuthenticatedStaffUsersUserIdRouteRoute
  AuthenticatedStaffReportsReportIdRoute: typeof AuthenticatedStaffReportsReportIdRoute
  AuthenticatedStaffReportsIndexRoute: typeof AuthenticatedStaffReportsIndexRoute
}

const AuthenticatedStaffRouteRouteChildren: AuthenticatedStaffRouteRouteChildren =
  {
    AuthenticatedStaffActivityRoute: AuthenticatedStaffActivityRoute,
    AuthenticatedStaffAppealsRoute: AuthenticatedStaffAppealsRoute,
    AuthenticatedStaffChangelogsRoute: AuthenticatedStaffChangelogsRoute,
    AuthenticatedStaffSupportRoute: AuthenticatedStaffSupportRoute,
    AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
    AuthenticatedStaffUsersUserIdRouteRoute:
      AuthenticatedStaffUsersUserIdRouteRoute,
    AuthenticatedStaffReportsReportIdRoute:
      AuthenticatedStaffReportsReportIdRoute,
    AuthenticatedStaffReportsIndexRoute: AuthenticatedStaffReportsIndexRoute,
  }

const AuthenticatedStaffRouteRouteWithChildren =
  AuthenticatedStaffRouteRoute._addFileChildren(
    AuthenticatedStaffRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtmeRouteRoute: typeof AuthenticatedAtmeRouteRouteWithChildren
  AuthenticatedAvatarRouteRoute: typeof AuthenticatedAvatarRouteRoute
  AuthenticatedFeedRouteRoute: typeof AuthenticatedFeedRouteRouteWithChildren
  AuthenticatedProfileRouteRoute: typeof AuthenticatedProfileRouteRoute
  AuthenticatedSpacesRouteRoute: typeof AuthenticatedSpacesRouteRouteWithChildren
  AuthenticatedStaffRouteRoute: typeof AuthenticatedStaffRouteRouteWithChildren
  AuthenticatedSupportTicketsTicketIdRoute: typeof AuthenticatedSupportTicketsTicketIdRoute
  AuthenticatedSupportTicketsIndexRoute: typeof AuthenticatedSupportTicketsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtmeRouteRoute: AuthenticatedAtmeRouteRouteWithChildren,
  AuthenticatedAvatarRouteRoute: AuthenticatedAvatarRouteRoute,
  AuthenticatedFeedRouteRoute: AuthenticatedFeedRouteRouteWithChildren,
  AuthenticatedProfileRouteRoute: AuthenticatedProfileRouteRoute,
  AuthenticatedSpacesRouteRoute: AuthenticatedSpacesRouteRouteWithChildren,
  AuthenticatedStaffRouteRoute: AuthenticatedStaffRouteRouteWithChildren,
  AuthenticatedSupportTicketsTicketIdRoute:
    AuthenticatedSupportTicketsTicketIdRoute,
  AuthenticatedSupportTicketsIndexRoute: AuthenticatedSupportTicketsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AppealRoute: AppealRoute,
  DownloadRoute: DownloadRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetRoute: ResetRoute,
  SupportRoute: SupportRoute,
  TosRoute: TosRoute,
  UsersUsernameRouteRoute: UsersUsernameRouteRoute,
  ConnectionsCallbackRoute: ConnectionsCallbackRoute,
  InviteCodeRoute: InviteCodeRoute,
  SpotifyCallbackRoute: SpotifyCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
